// Phase 25: Gallery system implementation
// Nodes:
//   Tier 1 (parallel, deps: phase-24-term):
//     fr-compile-prompts-intent, fr-emit-node-type, fr-strategies, fr-gallery-core, fr-cost-estimator
//   Tier 2 (parallel after tier 1):
//     fr-gallery-templates (deps: fr-gallery-core)
//     fr-emit-gallery-core (deps: fr-emit-node-type, fr-strategies)
//   Tier 3:
//     fr-blend (deps: fr-emit-gallery-core)
//   Tier 4 (CLI — sequential, same file):
//     fr-plan-gallery-cli (deps: fr-gallery-core, fr-gallery-templates, fr-cost-estimator)
//     fr-emit-gallery-cli (deps: fr-plan-gallery-cli, fr-emit-gallery-core, fr-blend, fr-emit-node-type)
//   Tier 5 (parallel tests):
//     fr-gallery-tests (deps: fr-plan-gallery-cli, fr-gallery-core, fr-cost-estimator, fr-gallery-templates)
//     fr-emit-gallery-tests (deps: fr-emit-gallery-cli, fr-emit-gallery-core, fr-blend, fr-strategies)
//     fr-intent-selfcheck-tests (deps: fr-compile-prompts-intent)
//   Tier 6:
//     phase-25-term (deps: all tests)
// Then: term.deps updated to ['phase-25-term']

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Graph } from '../src/protocol.ts';

const root = process.cwd();
const headPath = join(root, '.roadmap/head.json');
const dag = JSON.parse(readFileSync(headPath, 'utf-8')) as Graph<string>;
const nodes = dag.nodes as Record<string, any>;

const newNodes: Record<string, any> = {

  // ── Tier 1: independent, all start from phase-24-term ────────────────────

  'fr-impl-init': {
    id: 'fr-impl-init',
    desc: 'Phase 25 gate — existing files available as ambient context for gallery implementation',
    produces: [],
    consumes: [],
    ambient: [
      'src/lib/intent-evaluator.ts',  // readEvaluations — consumed by compile-prompts-intent + tests
      'src/lib/compile-prompts.ts',   // existing impl — enhanced by fr-compile-prompts-intent
      'src/protocol.ts',              // existing protocol — extended by fr-emit-node-type
    ],
    deps: ['phase-24-term'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/intent-evaluator.ts' },
      { type: 'artifact-exists', target: 'src/lib/compile-prompts.ts' },
    ],
    idempotent: true,
  },

  'fr-compile-prompts-intent': {
    id: 'fr-compile-prompts-intent',
    desc: [
      'Enhance src/lib/compile-prompts.ts: intent rules in validate[] emit annotated self-check items',
      'with failure mode hints from evaluation history.',
      '',
      'Currently buildVerificationChecklist() emits:',
      '  case "intent": return `- [ ] Intent (${rule.evaluator}): "${rule.statement}"`',
      '',
      'Required change:',
      '  1. Add buildIntentSelfCheck(validate: ValidationRule[], nodeId: string, repoRoot: string): string',
      '     - For each intent rule: emit "- [ ] \\"${statement}\\" (threshold: ${confidence}, evaluator: ${evaluator})"',
      '     - Call readEvaluations(nodeId, repoRoot) from src/lib/intent-evaluator.ts',
      '     - Filter by rule.statement, find last failing record (r.pass === false)',
      '     - If found: emit "      Known failure mode: ${lastFailure.reasoning}"',
      '     - If found && lastFailure.evidence.length: emit "      Evidence: ${lastFailure.evidence.join(", ")}"',
      '  2. In fillTemplate(): call buildIntentSelfCheck for intent rules, append as "### Intent (self-check)" subsection',
      '     in the Verification section, after deterministic items.',
      '     Signature change: fillTemplate(node, env, cluster?, repoRoot?) — repoRoot optional for backward compat.',
      '  3. compilePrompts(): pass repoRoot through to fillTemplate.',
      '',
      'Do NOT change the existing deterministic checklist items. The intent section is additive.',
      'Do NOT lower confidence thresholds — hints enrich prompts, they do not relax gates.',
      '',
      'consumes: src/lib/intent-evaluator.ts (readEvaluations export)',
    ].join('\n'),
    produces: ['src/lib/compile-prompts.ts'],
    consumes: [],
    ambient: ['src/lib/intent-evaluator.ts'],
    deps: ['fr-impl-init'],
    validate: [
      { type: 'shell', command: 'grep -q "buildIntentSelfCheck" src/lib/compile-prompts.ts' },
      { type: 'shell', command: 'grep -q "readEvaluations" src/lib/compile-prompts.ts' },
      { type: 'shell', command: 'grep -q "Known failure mode" src/lib/compile-prompts.ts' },
      {
        type: 'intent',
        statement: 'Intent self-check items include failure mode hint from evaluation history when prior failures exist, but history never adjusts confidence thresholds',
        confidence: 0.85,
        evaluator: 'self',
        context: ['src/lib/compile-prompts.ts'],
      },
    ],
    idempotent: true,
  },

  'fr-emit-node-type': {
    id: 'fr-emit-node-type',
    desc: [
      'Add EmitGalleryNodeSpec type and nodeType discriminant to src/protocol.ts.',
      '',
      'Add to protocol.ts:',
      '  export interface EmitGalleryNodeSpec {',
      '    id: string',
      '    nodeType: "emit-gallery"           // discriminant, distinct from mode',
      '    candidates: number                 // how many implementations to generate',
      '    strategies: string[]               // e.g. ["faithful", "minimal", "robust", "budget"]',
      '    selectionMode: "auto" | "manual"   // auto = LLM selects via Judgment',
      '    validate: ValidationRule[]         // gate suite applied to each candidate',
      '    produces: string[]',
      '    deps?: string[]',
      '    desc?: string',
      '  }',
      '',
      '  Add to NodeSpec<TAll, TSelf>: nodeType?: "execute" | "emit-gallery"',
      '  (mode is already "execute" | "plan" — nodeType is a separate dispatch dimension)',
      '',
      '  Export EmitGalleryNodeSpec from protocol.ts.',
      '',
      'Do NOT change ValidationRule, Graph, or Orientation types. Additive only.',
    ].join('\n'),
    produces: ['src/protocol.ts'],
    consumes: [],
    deps: ['fr-impl-init'],
    validate: [
      { type: 'shell', command: 'grep -q "EmitGalleryNodeSpec" src/protocol.ts' },
      { type: 'shell', command: 'grep -q "nodeType.*emit-gallery" src/protocol.ts' },
      { type: 'shell', command: 'npx tsc --noEmit 2>&1 | head -5' },
    ],
    idempotent: true,
  },

  'fr-strategies': {
    id: 'fr-strategies',
    desc: [
      'Create src/lib/strategies/ — generation strategy definitions for emit-gallery.',
      '',
      'Create src/lib/strategies/index.ts exporting:',
      '  export interface StrategySpec {',
      '    id: string                  // "faithful" | "minimal" | "robust" | "budget"',
      '    label: string               // human-readable name',
      '    systemPrompt: string        // injected as system prompt for the generator',
      '    model: string               // e.g. "claude-opus-4-6" | "claude-haiku-4-5-20251001"',
      '    estimatedCostMultiplier: number  // relative cost vs baseline (1.0 = baseline)',
      '  }',
      '  export const STRATEGIES: StrategySpec[]',
      '  export function getStrategy(id: string): StrategySpec',
      '',
      'Four strategies in STRATEGIES:',
      '  faithful: Opus, spec-literal, no embellishment. systemPrompt emphasizes exact spec adherence.',
      '  minimal: Haiku, fewest files, simplest architecture. systemPrompt emphasizes reduction.',
      '  robust: Opus, defensive coding, comprehensive error handling. systemPrompt emphasizes edge cases.',
      '  budget: Haiku, same spec input as faithful. systemPrompt identical to faithful. costMultiplier ~0.15.',
      '',
      'File: src/lib/strategies/index.ts (single file, no subdirectory needed)',
    ].join('\n'),
    produces: ['src/lib/strategies/index.ts'],
    consumes: [],
    deps: ['fr-impl-init'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/strategies/index.ts' },
      { type: 'shell', command: "grep -q 'export interface StrategySpec' src/lib/strategies/index.ts" },
      { type: 'shell', command: 'grep -q "faithful.*minimal.*robust.*budget" src/lib/strategies/index.ts' },
      { type: 'shell', command: 'grep -q "getStrategy" src/lib/strategies/index.ts' },
    ],
    idempotent: true,
  },

  'fr-gallery-core': {
    id: 'fr-gallery-core',
    desc: [
      'Create src/lib/gallery.ts — plan gallery core: types, Pareto filtering, cardinal risk, candidate generation.',
      '',
      'Exports:',
      '  export interface TemplateParams {',
      '    emitStrategy: "single-pass" | "two-stage" | "per-cluster"',
      '    gateOrdering: "parallel" | "serial" | "cheapest-first"',
      '    preExpansion: "none" | "from-history" | "from-spec-complexity"',
      '    modelAllocation: "opus-all" | "opus-emit+haiku-fix" | "haiku-emit+opus-judge"',
      '    convergence: "fixed-passes" | "until-clean" | "budget-capped"',
      '  }',
      '',
      '  export interface GalleryCandidate {',
      '    id: string                    // "aggressive" | "corrective" | "staged" | "budget"',
      '    label: string',
      '    summary: string',
      '    parameters: TemplateParams',
      '    dag: Record<string, any>      // head.json-compatible DAGSpec',
      '    estimates: {',
      '      nodes: number',
      '      maxExpansion: number',
      '      wallClockMinutes: number',
      '      costUSD: number',
      '      risk: number                // cardinal: 0.0–1.0 = 1 - (historicalSuccessRate * gateConvergenceRate)',
      '    }',
      '    gateProfile: { deterministic: number; intent: number; runtime: number }',
      '    historySignal?: {',
      '      priorFailureClasses: string[]',
      '      preExpanded: string[]',
      '      templateSuccessRate: number',
      '    }',
      '  }',
      '',
      '  export function computeRisk(historicalSuccessRate: number, gateConvergenceRate: number): number',
      '    // risk = 1 - (historicalSuccessRate * gateConvergenceRate)',
      '    // No history → both rates default to 0 → risk = 1.0',
      '',
      '  export function paretoFilter(candidates: GalleryCandidate[]): GalleryCandidate[]',
      '    // Prune dominated candidates. A is dominated by B if:',
      '    //   B.estimates.costUSD <= A.estimates.costUSD AND',
      '    //   B.estimates.wallClockMinutes <= A.estimates.wallClockMinutes AND',
      '    //   B.estimates.risk <= A.estimates.risk AND at least one strictly less.',
      '    // Target: 3-4 survivors.',
      '    // On cold start (all risk=1.0): conservative template always survives.',
      '',
      '  export function generateCandidates(specSource: string, historyDir?: string): GalleryCandidate[]',
      '    // Generate all template combinations, score with computeRisk, run paretoFilter.',
      '    // historyDir = path to .roadmap/evaluations/ (optional, skipped if missing)',
      '',
      'No Anthropic API calls. This is pure data generation + filtering.',
    ].join('\n'),
    produces: ['src/lib/gallery.ts'],
    consumes: [],
    deps: ['fr-impl-init'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/gallery.ts' },
      { type: 'shell', command: 'grep -q "GalleryCandidate" src/lib/gallery.ts' },
      { type: 'shell', command: 'grep -q "paretoFilter" src/lib/gallery.ts' },
      { type: 'shell', command: 'grep -q "computeRisk" src/lib/gallery.ts' },
      {
        type: 'intent',
        statement: 'Pareto filtering uses cardinal risk = 1 - (historicalSuccessRate × gateConvergenceRate), defaults to 1.0 on cold start, and conservative template always survives when all candidates share risk=1.0',
        confidence: 0.85,
        evaluator: 'self',
        context: ['src/lib/gallery.ts'],
      },
    ],
    idempotent: true,
  },

  'fr-cost-estimator': {
    id: 'fr-cost-estimator',
    desc: [
      'Create src/lib/cost-estimator.ts — history-based cost and time estimation for gallery candidates.',
      '',
      'Exports:',
      '  export interface CostEstimate {',
      '    wallClockMinutes: number',
      '    costUSD: number',
      '    confidence: "cold-start" | "low" | "medium" | "high"  // based on history sample size',
      '  }',
      '',
      '  export function estimateCost(params: {',
      '    nodeCount: number,',
      '    modelAllocation: TemplateParams["modelAllocation"],',
      '    checkpointDir?: string,       // .roadmap/checkpoints/ for duration baselines',
      '    evaluationsDir?: string,      // .roadmap/evaluations/ for gate convergence history',
      '  }): CostEstimate',
      '',
      '  Cost model:',
      '    opus: $0.015/1k input tokens, ~0.5k tokens/node average',
      '    haiku: $0.00025/1k input tokens, same node count',
      '  Duration model:',
      '    Read checkpoint durations from checkpointDir if available',
      '    Fallback: 1.5 min/node for opus, 0.5 min/node for haiku',
      '  Confidence:',
      '    cold-start = no history files found',
      '    low = 1-2 prior runs',
      '    medium = 3-9 prior runs',
      '    high = 10+ prior runs',
      '',
      'Import TemplateParams from src/lib/gallery.ts.',
      'No Anthropic API calls.',
    ].join('\n'),
    produces: ['src/lib/cost-estimator.ts'],
    consumes: ['src/lib/gallery.ts'],
    deps: ['fr-gallery-core'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/cost-estimator.ts' },
      { type: 'shell', command: 'grep -q "estimateCost" src/lib/cost-estimator.ts' },
      { type: 'shell', command: 'grep -q "CostEstimate" src/lib/cost-estimator.ts' },
      { type: 'shell', command: 'grep -q "cold-start" src/lib/cost-estimator.ts' },
    ],
    idempotent: true,
  },

  // ── Tier 2 ────────────────────────────────────────────────────────────────

  'fr-gallery-templates': {
    id: 'fr-gallery-templates',
    desc: [
      'Create src/lib/gallery-templates/index.ts — four named plan templates as GalleryCandidate factories.',
      '',
      'Exports:',
      '  export interface TemplateDefinition {',
      '    id: "aggressive" | "corrective" | "staged" | "budget"',
      '    label: string',
      '    summary: string',
      '    parameters: TemplateParams',
      '    buildDag(specSource: string, historyFailureClasses?: string[]): Record<string, any>',
      '    // Returns head.json-compatible partial DAGSpec (nodes + deps, no id/init/term)',
      '  }',
      '  export const TEMPLATES: TemplateDefinition[]',
      '  export function buildGallery(specSource: string, historyDir?: string): GalleryCandidate[]',
      '    // Instantiate all 4 templates, score with estimateCost + computeRisk, return Pareto-filtered set.',
      '',
      'Template DAG shapes:',
      '  aggressive:  emit-gallery(4 candidates, parallel) → runtime-gate → converged',
      '  corrective:  emit-gallery(4 candidates, serial gates) → intent → runtime-gate → converged',
      '               preExpansion: "from-history" — adds fix nodes for known failure classes',
      '  staged:      emit-gallery(skeleton, 3 candidates) → emit-gallery(features, 3 candidates) → test → intent → runtime-gate → converged',
      '  budget:      emit-gallery(4 haiku candidates) → compile → test → runtime-gate → converged',
      '',
      'Import GalleryCandidate, TemplateParams, computeRisk, paretoFilter from src/lib/gallery.ts.',
      'Import estimateCost from src/lib/cost-estimator.ts.',
    ].join('\n'),
    produces: ['src/lib/gallery-templates/index.ts'],
    consumes: ['src/lib/gallery.ts', 'src/lib/cost-estimator.ts'],
    deps: ['fr-gallery-core', 'fr-cost-estimator'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/gallery-templates/index.ts' },
      { type: 'shell', command: 'grep -q "TemplateDefinition" src/lib/gallery-templates/index.ts' },
      { type: 'shell', command: 'grep -q "buildGallery" src/lib/gallery-templates/index.ts' },
      { type: 'shell', command: 'grep -q "aggressive.*corrective.*staged.*budget" src/lib/gallery-templates/index.ts' },
    ],
    idempotent: true,
  },

  'fr-emit-gallery-core': {
    id: 'fr-emit-gallery-core',
    desc: [
      'Create src/lib/emit-gallery.ts — multi-candidate code generation: parallel execution, gating, scorecard.',
      '',
      'Exports:',
      '  export interface CandidateResult {',
      '    id: string',
      '    strategy: string',
      '    files: Record<string, string>  // path → content',
      '    deterministic: {',
      '      tsc: { pass: boolean; errors?: string[] }',
      '      vitest: { pass: boolean; passed: number; failed: number; coverage: number }',
      '      build: { pass: boolean; outputs?: string[] }',
      '    }',
      '    intent: Array<{ statement: string; pass: boolean; confidence: number; reasoning: string; evidence: string[] }>',
      '    summary: { loc: number; fileCount: number; deterministicPass: boolean; intentScore: string; estimatedCost: number }',
      '  }',
      '',
      '  export type FileToIntents = Record<string, string[]>',
      '',
      '  export function buildFileToIntents(validateRules: ValidationRule[]): FileToIntents',
      '    // Invert intent rule contextPaths: statement→files → files→statements',
      '    // Rule with no contextPaths: skip (requires explicit context for blend substitutability)',
      '',
      '  export interface ConvergenceConfig {',
      '    maxFixPasses: number          // per gate, default 3',
      '    escalateAfter: "all-candidates-fail" | "fix-pass-stall"',
      '    escalateTo: "human" | "opus-review"',
      '  }',
      '',
      '  export interface GalleryFailure {',
      '    unreachable: string           // intent statement that no candidate satisfied',
      '    bestConfidence: number',
      '    threshold: number',
      '    candidates: number',
      '    diagnosis: string             // e.g. "all candidates used @media prefers-color-scheme"',
      '  }',
      '',
      '  export interface GalleryRunResult {',
      '    candidates: CandidateResult[]',
      '    survivors: CandidateResult[]  // passed deterministic gates',
      '    intentSurvivors: CandidateResult[]  // also passed intent gates',
      '    failures: GalleryFailure[]    // unreachable intents',
      '    scorecard: string             // ASCII table for CLI rendering',
      '  }',
      '',
      '  export async function runGallery(opts: {',
      '    nodeSpec: EmitGalleryNodeSpec,',
      '    strategies: StrategySpec[],',
      '    workDir: string,              // .roadmap/gallery/',
      '    convergence?: ConvergenceConfig,',
      '  }): Promise<GalleryRunResult>',
      '    // Generates candidates in parallel (Promise.all), gates each, builds scorecard.',
      '    // Does NOT make real LLM calls — stubs candidates as empty file sets for now.',
      '    // Real LLM dispatch is a future FR. This FR establishes the pipeline + types.',
      '',
      'Import EmitGalleryNodeSpec from src/protocol.ts.',
      'Import StrategySpec from src/lib/strategies/index.ts.',
      'Import ValidationRule from src/protocol.ts.',
      '',
      'Key invariant: gallery is diversity not retry.',
      '  If all candidates fail the same intent → GalleryFailure, not loop.',
      '  maxFixPasses applies per gate after selection, not to generation.',
    ].join('\n'),
    produces: ['src/lib/emit-gallery.ts'],
    consumes: ['src/protocol.ts', 'src/lib/strategies/index.ts'],
    deps: ['fr-emit-node-type', 'fr-strategies'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/emit-gallery.ts' },
      { type: 'shell', command: 'grep -q "buildFileToIntents" src/lib/emit-gallery.ts' },
      { type: 'shell', command: 'grep -q "GalleryRunResult" src/lib/emit-gallery.ts' },
      { type: 'shell', command: 'grep -q "ConvergenceConfig" src/lib/emit-gallery.ts' },
      { type: 'shell', command: 'grep -q "GalleryFailure" src/lib/emit-gallery.ts' },
      { type: 'shell', command: "grep -q 'import.*StrategySpec.*from.*strategies' src/lib/emit-gallery.ts" },
      {
        type: 'intent',
        statement: 'Gallery treats maxFixPasses as a per-gate budget after selection, not a generation retry count; all-candidates-fail produces GalleryFailure with structured evidence rather than additional generation attempts',
        confidence: 0.85,
        evaluator: 'self',
        context: ['src/lib/emit-gallery.ts'],
      },
    ],
    idempotent: true,
  },

  // ── Tier 3 ────────────────────────────────────────────────────────────────

  'fr-blend': {
    id: 'fr-blend',
    desc: [
      'Create src/lib/blend.ts — multi-candidate file merging with intent-gate conflict resolution.',
      '',
      'Exports:',
      '  export interface BlendSpec {',
      '    primary: string     // candidate id — base architecture source',
      '    donors: string[]    // candidates to pull cheaper files from',
      '  }',
      '',
      '  export interface BlendResult {',
      '    files: Record<string, string>  // merged file set',
      '    substitutions: Array<{ path: string; from: string; reason: string }>',
      '    reverted: Array<{ path: string; reason: string }>',
      '    deterministicPass: boolean',
      '    intentScore: string',
      '  }',
      '',
      '  export function blendCandidates(',
      '    candidates: CandidateResult[],',
      '    spec: BlendSpec,',
      '    fileToIntents: FileToIntents,',
      '  ): BlendResult',
      '',
      'Algorithm:',
      '  1. Start with primary candidate files.',
      '  2. For each donor candidate, for each file in donor:',
      '     a. Look up fileToIntents[path] → list of intent statements covering this file.',
      '     b. If the donor passed ALL those intents AND donor.summary.loc < primary.summary.loc → substitute.',
      '     c. Re-check deterministic validators (tsc pass, vitest pass) on the blended set.',
      '        If deterministic gate breaks → revert the substitution.',
      '  3. Re-run intent evaluation on blended result (use donor intent results where unchanged,',
      '     mark substituted files as needing re-evaluation).',
      '  4. If blend fails gates that all source candidates passed → discard, return primary files.',
      '',
      'Note: files with empty fileToIntents[path] are not substitutable (conservative).',
      '  This is by design — see FR-EMIT-GALLERY open question 5.',
      '',
      'Import CandidateResult, FileToIntents from src/lib/emit-gallery.ts.',
    ].join('\n'),
    produces: ['src/lib/blend.ts'],
    consumes: ['src/lib/emit-gallery.ts'],
    deps: ['fr-emit-gallery-core'],
    validate: [
      { type: 'artifact-exists', target: 'src/lib/blend.ts' },
      { type: 'shell', command: 'grep -q "blendCandidates" src/lib/blend.ts' },
      { type: 'shell', command: 'grep -q "BlendResult" src/lib/blend.ts' },
      { type: 'shell', command: 'grep -q "fileToIntents" src/lib/blend.ts' },
      {
        type: 'intent',
        statement: 'Blend substitutes donor files only when the donor passed ALL intent statements in fileToIntents[path], and reverts any substitution that breaks a deterministic gate',
        confidence: 0.85,
        evaluator: 'self',
        context: ['src/lib/blend.ts'],
      },
    ],
    idempotent: true,
  },

  // ── Tier 4: CLI (sequential — both modify bin/roadmap.ts) ─────────────────

  'fr-plan-gallery-cli': {
    id: 'fr-plan-gallery-cli',
    desc: [
      'Add `roadmap plan --gallery` command to bin/roadmap.ts.',
      '',
      'New command: plan --gallery [--from <specFile>] [--select <id>] [--evaluate <json>] [--json]',
      '',
      'Handler cmdPlanGallery():',
      '  1. Parse --from <specFile> (defaults to first .specify/specs/**/*.md found, or empty string)',
      '  2. Parse --select <id> to commit a previously-generated candidate',
      '  3. Parse --evaluate <json> for LLM judgment (same Judgment schema as complete --evaluate)',
      '  4. If no --select and no --evaluate:',
      '     a. Call buildGallery(specSource, repoRoot + "/.roadmap/evaluations")',
      '     b. Render ASCII table comparison (id, nodes, wallClockMinutes, costUSD, risk)',
      '     c. Show topology diagram per candidate (compact: "emit → compile ─┬─ test ─┬─ runtime")',
      '     d. Show recommendation (lowest risk)',
      '     e. Output "Select [A/B/C/D]:"',
      '  5. If --evaluate <json>:',
      '     a. Parse Judgment[] from json',
      '     b. Validate confidence >= 0.7 (minimum bar for plan selection)',
      '     c. Record to .roadmap/evaluations/plan-selection.jsonl with phase: "plan-selection:<runId>"',
      '     d. Write selected candidate dag as .roadmap/head.json (AFTER backing up existing as .roadmap/head-prev.json)',
      '     e. Output: { selected: id, committed: true, headPath: ".roadmap/head.json" }',
      '  6. If --select <id>: same as --evaluate but without confidence requirement (manual override)',
      '',
      'Wire in main switch: case "plan": if (args.includes("--gallery")) ...',
      '',
      'Import buildGallery from src/lib/gallery-templates/index.ts',
      'Import estimateCost from src/lib/cost-estimator.ts',
      '',
      'After adding the command, run: npx tsc --noEmit to verify no type errors.',
    ].join('\n'),
    produces: ['bin/roadmap.ts'],
    consumes: ['src/lib/gallery.ts', 'src/lib/gallery-templates/index.ts', 'src/lib/cost-estimator.ts'],
    deps: ['fr-gallery-core', 'fr-gallery-templates', 'fr-cost-estimator'],
    validate: [
      { type: 'shell', command: 'grep -q "cmdPlanGallery\\|plan.*gallery" bin/roadmap.ts' },
      { type: 'shell', command: 'grep -q "buildGallery" bin/roadmap.ts' },
      { type: 'shell', command: 'grep -q "plan-selection" bin/roadmap.ts' },
      { type: 'shell', command: 'npx tsc --noEmit' },
    ],
    idempotent: true,
  },

  'fr-emit-gallery-cli': {
    id: 'fr-emit-gallery-cli',
    desc: [
      'Add `roadmap emit --gallery` command and emit-gallery complete dispatch to bin/roadmap.ts.',
      '',
      'Two changes to bin/roadmap.ts:',
      '',
      '1. New command: emit --gallery [--candidates N] [--from <spec>] [--select <id>] [--blend <A+B>] [--evaluate <json>] [--json]',
      '   Handler cmdEmitGallery():',
      '   a. Parse flags',
      '   b. Load DAG, find emit-gallery nodes (nodeType === "emit-gallery")',
      '   c. Call runGallery({ nodeSpec, strategies: STRATEGIES, workDir: repoRoot+"/.roadmap/gallery/" })',
      '   d. Render scorecard ASCII table (Candidate, Files, LOC, tsc, vitest, build, intent, cost)',
      '   e. Show: "Deterministic survivors: ...", "Intent survivors: ..."',
      '   f. If --blend <A+B>: call blendCandidates(), re-evaluate, show blend result',
      '   g. If --evaluate <json>: parse Judgment, record to .roadmap/evaluations/emit-selection.jsonl,',
      '      copy winning candidate files to main working tree, commit',
      '   h. If --select <id>: same as --evaluate without confidence check',
      '',
      '2. In cmdComplete handler, add dispatch on node.nodeType:',
      '   After loading nodeSpec, check: if ((nodeSpec as any).nodeType === "emit-gallery") {',
      '     await handleEmitGalleryComplete(nodeSpec, repoRoot)',
      '     return  // skip standard validation',
      '   }',
      '   handleEmitGalleryComplete() = runGallery + auto-select best intent survivor + commit files.',
      '',
      'Wire in main switch: case "emit": if (args.includes("--gallery")) ...',
      '',
      'Import runGallery from src/lib/emit-gallery.ts',
      'Import blendCandidates from src/lib/blend.ts',
      'Import STRATEGIES from src/lib/strategies/index.ts',
      '',
      'After adding both changes, run: npx tsc --noEmit to verify no type errors.',
    ].join('\n'),
    produces: ['bin/roadmap.ts'],
    consumes: ['src/lib/emit-gallery.ts', 'src/lib/blend.ts', 'src/lib/strategies/index.ts', 'src/protocol.ts'],
    deps: ['fr-plan-gallery-cli', 'fr-emit-gallery-core', 'fr-blend', 'fr-emit-node-type'],
    validate: [
      { type: 'shell', command: 'grep -q "cmdEmitGallery\\|emit.*gallery" bin/roadmap.ts' },
      { type: 'shell', command: 'grep -q "runGallery" bin/roadmap.ts' },
      { type: 'shell', command: 'grep -q "emit-gallery.*nodeType\\|nodeType.*emit-gallery" bin/roadmap.ts' },
      { type: 'shell', command: 'npx tsc --noEmit' },
    ],
    idempotent: true,
  },

  // ── Tier 5: Tests (parallel) ──────────────────────────────────────────────

  'fr-gallery-tests': {
    id: 'fr-gallery-tests',
    desc: [
      'Tests for plan gallery: types, Pareto filtering, risk formula, cost estimation, template generation.',
      '',
      'File: tests/gallery.test.ts',
      '',
      'Test suites:',
      '  computeRisk():',
      '    - Both rates 1.0 → risk 0.0',
      '    - Both rates 0.0 → risk 1.0 (cold start: default to 0 → risk = 1.0)',
      '    - Mixed: (0.8 * 0.9) → risk = 1 - 0.72 = 0.28',
      '',
      '  paretoFilter():',
      '    - All candidates distinct → all survive (no domination)',
      '    - B dominates A (cheaper AND faster AND safer) → A removed',
      '    - Partial domination (cheaper but riskier) → both survive',
      '    - Cold start (all risk=1.0): conservative template (lowest cost estimate) survives',
      '    - Result always has 1–4 candidates',
      '',
      '  estimateCost():',
      '    - Cold start (no historyDir): confidence="cold-start", uses fallback rates',
      '    - Opus-all allocation: higher cost, lower or equal wallClockMinutes',
      '    - Haiku allocation: lower cost',
      '',
      '  buildGallery():',
      '    - Returns 3-4 candidates (Pareto filtered)',
      '    - Each has id, label, estimates, gateProfile',
      '    - Contains "corrective" template when history failure classes present',
      '',
      'Import from src/lib/gallery.ts and src/lib/cost-estimator.ts.',
    ].join('\n'),
    produces: ['tests/gallery.test.ts'],
    consumes: ['src/lib/gallery.ts', 'src/lib/cost-estimator.ts', 'src/lib/gallery-templates/index.ts'],
    deps: ['fr-plan-gallery-cli', 'fr-gallery-core', 'fr-cost-estimator', 'fr-gallery-templates'],
    validate: [
      { type: 'artifact-exists', target: 'tests/gallery.test.ts' },
      { type: 'shell', command: 'npx vitest run tests/gallery.test.ts --reporter=dot' },
    ],
    idempotent: true,
  },

  'fr-emit-gallery-tests': {
    id: 'fr-emit-gallery-tests',
    desc: [
      'Tests for emit gallery: buildFileToIntents, blendCandidates, convergence protocol, strategy specs.',
      '',
      'File: tests/emit-gallery.test.ts',
      '',
      'Test suites:',
      '  buildFileToIntents():',
      '    - Intent rule with contextPaths → inverted index',
      '    - Multiple rules with overlapping paths → all statements included',
      '    - Rule without contextPaths → excluded (conservative)',
      '',
      '  blendCandidates():',
      '    - Donor file passes all fileToIntents intents AND is smaller → substituted',
      '    - Donor file fails an intent → not substituted',
      '    - File not in fileToIntents (empty entry) → not substitutable',
      '    - Substitution breaks deterministic gate → reverted',
      '    - All-donors-fail → returns primary candidate files unchanged',
      '',
      '  ConvergenceConfig:',
      '    - runGallery with 4 strategies → GalleryRunResult with 4 candidates',
      '    - All candidates fail same intent → GalleryFailure in result.failures',
      '    - GalleryFailure includes bestConfidence, threshold, diagnosis',
      '',
      '  StrategySpec (from src/lib/strategies/index.ts):',
      '    - getStrategy("faithful") returns StrategySpec with model containing "opus"',
      '    - getStrategy("budget") returns StrategySpec with lower estimatedCostMultiplier',
      '    - getStrategy("unknown") throws',
      '    - STRATEGIES has exactly 4 entries',
      '',
      'Import from src/lib/emit-gallery.ts, src/lib/blend.ts, src/lib/strategies/index.ts.',
    ].join('\n'),
    produces: ['tests/emit-gallery.test.ts'],
    consumes: ['src/lib/emit-gallery.ts', 'src/lib/blend.ts', 'src/lib/strategies/index.ts'],
    deps: ['fr-emit-gallery-cli', 'fr-emit-gallery-core', 'fr-blend', 'fr-strategies'],
    validate: [
      { type: 'artifact-exists', target: 'tests/emit-gallery.test.ts' },
      { type: 'shell', command: 'npx vitest run tests/emit-gallery.test.ts --reporter=dot' },
    ],
    idempotent: true,
  },

  'fr-intent-selfcheck-tests': {
    id: 'fr-intent-selfcheck-tests',
    desc: [
      'Tests for compile-prompts intent self-check with history enrichment.',
      '',
      'File: tests/compile-prompts-intent.test.ts',
      '(Extend or create alongside existing compile-prompts tests.)',
      '',
      'Test suites:',
      '  buildIntentSelfCheck() — no history:',
      '    - Intent rule with no prior failures → emits statement + threshold, no hint',
      '',
      '  buildIntentSelfCheck() — with failing history:',
      '    - Prior failure exists → emits "Known failure mode: ${reasoning}"',
      '    - Prior failure with evidence → emits "Evidence: ..."',
      '    - Prior failure then pass (most recent is pass) → no hint emitted',
      '    - Multiple statements → only matching statement gets hint',
      '',
      '  compilePrompts() integration:',
      '    - Node with intent rule + history → compiled prompt contains "Known failure mode"',
      '    - Node with intent rule + no history → compiled prompt contains statement but no hint',
      '    - Deterministic checklist items still present alongside intent self-check',
      '',
      'Use tmp directory for fake .roadmap/evaluations/ records.',
      'Import fillTemplate, compilePrompts from src/lib/compile-prompts.ts.',
      'Import recordEvaluation, judgmentToRecord from src/lib/intent-evaluator.ts (for test setup).',
    ].join('\n'),
    produces: ['tests/compile-prompts-intent.test.ts'],
    consumes: ['src/lib/compile-prompts.ts'],
    ambient: ['src/lib/intent-evaluator.ts'],
    deps: ['fr-compile-prompts-intent'],
    validate: [
      { type: 'artifact-exists', target: 'tests/compile-prompts-intent.test.ts' },
      { type: 'shell', command: 'npx vitest run tests/compile-prompts-intent.test.ts --reporter=dot' },
    ],
    idempotent: true,
  },

  // ── Tier 6: Phase term ────────────────────────────────────────────────────

  'phase-25-term': {
    id: 'phase-25-term',
    desc: 'Phase 25 complete: gallery system ships — plan gallery, emit gallery, compile-prompts intent self-check, blend, strategies',
    produces: [],
    consumes: ['tests/gallery.test.ts', 'tests/emit-gallery.test.ts', 'tests/compile-prompts-intent.test.ts'],
    deps: ['fr-gallery-tests', 'fr-emit-gallery-tests', 'fr-intent-selfcheck-tests'],
    validate: [
      { type: 'shell', command: 'npx tsc --noEmit' },
      { type: 'shell', command: 'npx vitest run --reporter=dot' },
    ],
    idempotent: false,
  },
};

for (const [id, node] of Object.entries(newNodes)) {
  nodes[id] = node;
}

// Repoint term to phase-25-term
const term = nodes[dag.term] as any;
term.deps = term.deps.map((d: string) => d === 'phase-24-term' ? 'phase-25-term' : d);

writeFileSync(headPath, JSON.stringify(dag, null, 2) + '\n');
console.log(`Expanded: +${Object.keys(newNodes).length} nodes (phase-25). Total: ${Object.keys(nodes).length}`);
