/**
 * Auto-generate roadmap.ts from ProjectMetadata + BuildProcess
 *
 * Generates a minimal 3-node DAG:
 * init (project setup) → build → term (ready for deployment)
 *
 * The generated roadmap:
 * - Passes verify(), check() without user edits
 * - All nodes marked idempotent: true (agents can safely re-run)
 * - Can be extended with reconcile() to add custom phases
 */

import type { ProjectMetadata } from './project-metadata.schema.ts';
import type { NodeSpec, Graph } from './protocol.ts';
import { check, verify, define } from './protocol.ts';

export interface GeneratedDAG {
  sourceCode: string; // The roadmap.ts code
  dag: Graph<'init' | 'build' | 'term'>; // The parsed DAG
}

/**
 * Generate roadmap DAG from project metadata
 */
export function generateRoadmapDAG(
  projectId: string,
  metadata: ProjectMetadata,
  buildCommand: string,
): GeneratedDAG {
  const buildOutput = inferBuildOutput(metadata, buildCommand);
  const sourceFiles = inferSourceFiles(metadata);
  const configFiles = inferConfigFiles(metadata);

  const dag: Graph<'init' | 'build' | 'term'> = {
    id: projectId,
    desc: `Project roadmap for ${metadata.name} (auto-generated by roadmap integrate)`,
    init: 'init',
    term: 'term',
    nodes: {
      init: {
        id: 'init',
        desc: 'Initialize project: install dependencies, setup environment',
        produces: ['node_modules', '.git/hooks'],
        consumes: [],
        deps: [],
        idempotent: true,
      },
      build: {
        id: 'build',
        desc: `Build project: ${buildCommand}`,
        produces: buildOutput,
        consumes: [...sourceFiles, ...configFiles, 'package.json'],
        deps: ['init'],
        idempotent: true,
      },
      term: {
        id: 'term',
        desc: 'Project ready (build complete, artifacts available)',
        produces: [],
        consumes: buildOutput,
        deps: ['build'],
        idempotent: false,
      },
    },
  };

  // Validate the generated DAG
  try {
    define(dag); // Check structure
  } catch (e) {
    throw new Error(`Generated DAG failed define(): ${e instanceof Error ? e.message : String(e)}`);
  }

  const checkResult = check(dag);
  if (!checkResult.done) {
    throw new Error(`Generated DAG not fully connected: orphans=${checkResult.orphans}`);
  }

  const verifyErrors = verify(dag);
  if (verifyErrors.length) {
    throw new Error(`Generated DAG contract violations: ${verifyErrors.join(', ')}`);
  }

  const sourceCode = generateSourceCode(projectId, metadata, buildCommand, buildOutput, sourceFiles, configFiles);

  return { sourceCode, dag };
}

/**
 * Infer build output directory/files
 */
function inferBuildOutput(metadata: ProjectMetadata, buildCommand: string): string[] {
  // Common patterns
  if (buildCommand.includes('tsc')) return ['dist', 'lib', '*.d.ts'];
  if (buildCommand.includes('esbuild')) return ['dist'];
  if (buildCommand.includes('vite')) return ['dist'];
  if (buildCommand.includes('rollup')) return ['dist'];
  if (buildCommand.includes('webpack')) return ['dist'];
  if (buildCommand.includes('parcel')) return ['dist'];

  // Default based on package.json type
  if (metadata.packageJson?.type === 'module') return ['dist', '*.d.ts'];
  if (metadata.packageJson?.main) {
    const dir = metadata.packageJson.main.split('/')[0];
    return [dir || 'dist'];
  }

  return ['dist'];
}

/**
 * Infer source file patterns from project type
 */
function inferSourceFiles(metadata: ProjectMetadata): string[] {
  const files: string[] = [];

  if (metadata.projectType === 'typescript') {
    files.push('src/**/*.ts');
  } else if (metadata.projectType === 'javascript') {
    files.push('src/**/*.js');
  }

  if (metadata.projectType === 'webapp' || metadata.projectType === 'react') {
    files.push('src/**/*.tsx', 'src/**/*.jsx', 'src/**/*.ts', 'src/**/*.js');
  }

  if (!files.length) {
    files.push('src');
  }

  return files;
}

/**
 * Infer config files based on project type
 */
function inferConfigFiles(metadata: ProjectMetadata): string[] {
  const configs: string[] = [];

  if (metadata.projectType === 'typescript') {
    configs.push('tsconfig.json');
  }

  if (metadata.buildCommand?.includes('tsc') || metadata.buildCommand?.includes('TypeScript')) {
    configs.push('tsconfig.json');
  }

  if (metadata.packageJson?.jest || metadata.packageJson?.vitest) {
    configs.push('vitest.config.ts', 'jest.config.js');
  }

  // Always include these
  configs.push('package.json');

  return [...new Set(configs)].filter(c => c && c !== 'package.json');
}

/**
 * Generate roadmap.ts source code
 */
function generateSourceCode(
  projectId: string,
  metadata: ProjectMetadata,
  buildCommand: string,
  buildOutput: string[],
  sourceFiles: string[],
  configFiles: string[],
): string {
  const buildOutputStr = buildOutput.map(o => `    '${o}',`).join('\n');
  const sourceFilesStr = sourceFiles.map(s => `    '${s}',`).join('\n');
  const configFilesStr = configFiles.map(c => `    '${c}',`).join('\n');
  const consumesStr = [...sourceFiles, ...configFiles]
    .map(s => `    '${s}',`)
    .join('\n');

  return `#!/usr/bin/env node
/**
 * Project roadmap
 *
 * Auto-generated by: roadmap integrate
 * Date: ${new Date().toISOString()}
 *
 * This DAG defines the project lifecycle:
 * init → build → term
 *
 * To extend: use reconcile(dag, fwd, bwd) to add custom phases
 */

import { define, graph } from 'roadmap/protocol';

export default define(graph({
  id: '${projectId}',
  desc: 'Project roadmap for ${metadata.name}',
  init: 'init',
  term: 'term',
  nodes: {
    init: {
      id: 'init',
      desc: 'Initialize project: install dependencies, setup environment',
      produces: [
        'node_modules',
        '.git/hooks',
      ],
      consumes: [],
      deps: [],
      idempotent: true,
    },
    build: {
      id: 'build',
      desc: 'Build project: ${buildCommand}',
      produces: [
${buildOutputStr}
      ],
      consumes: [
${consumesStr}
      ],
      deps: ['init'],
      idempotent: true,
    },
    term: {
      id: 'term',
      desc: 'Project ready (build complete, artifacts available)',
      produces: [],
      consumes: [
${buildOutputStr}
      ],
      deps: ['build'],
      idempotent: false,
    },
  },
}));

/**
 * To use this roadmap in your project:
 *
 * 1. Check your position:
 *    import { orient } from 'roadmap/protocol';
 *    import roadmap from './roadmap.ts';
 *    const pos = orient(roadmap, (a) => existsSync(a));
 *    console.log(pos.position, pos.produces);
 *
 * 2. Execute phases:
 *    while (pos.position !== roadmap.term) {
 *      // Create pos.produces
 *      // Commit
 *      // Re-orient
 *    }
 *
 * 3. Add custom phases:
 *    Use reconcile() to identify gaps, then expand the DAG
 *    before this one to add test, lint, deploy phases
 */
`;
}

/**
 * Validate that generated DAG satisfies all constraints
 */
export function validateGeneratedDAG(dag: Graph<any>): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  try {
    define(dag);
  } catch (e) {
    errors.push(`define() failed: ${e instanceof Error ? e.message : String(e)}`);
  }

  const checkResult = check(dag);
  if (!checkResult.done) {
    errors.push(`DAG not fully connected: orphans=${checkResult.orphans.join(',')}`);
  }

  const verifyErrors = verify(dag);
  if (verifyErrors.length) {
    errors.push(...verifyErrors);
  }

  // All generated nodes must be idempotent (can safely re-run)
  for (const [nodeId, node] of Object.entries(dag.nodes)) {
    if (nodeId !== dag.term && !node.idempotent) {
      errors.push(`Non-terminal node "${nodeId}" must be idempotent=true`);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
